version: 2
jobs:
  build:
    working_directory: ~/tmp

    docker: 
      - image: circleci/node:7.10

    steps:
      - checkout

      # Download and cache dependecies
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json"}}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      # run test
      - run: npm test